# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MQTT Bed
version: "1.0.0"
slug: mqtt-bed
description: IoT Bed via BLE
url: "https://github.com/dstarikov/hass-mqtt-bed"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  bed_type: "serta"
  bed_address: "7C:EC:79:FF:6D:02"
schema:
  bed_type: "list(dewertokin|serta|jiecang)"
  bed_address: "match(^[A-z0-9]{2}:[A-z0-9]{2}:[A-z0-9]{2}:[A-z0-9]{2}:[A-z0-9]{2}:[A-z0-9]{2}$)"
image: "ghcr.io/dstarikov/{arch}-hass-mqtt-bed"
