# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MQTT Bed
version: "1.0.3"
slug: mqtt-bed
description: IoT Bed via BLE
url: "https://github.com/dstarikov/hass-mqtt-bed"
host_network: true
host_dbus: true
hassio_api: true
privileged:
  - "NET_ADMIN"
  - "SYS_RAWIO"
  - "SYS_ADMIN"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  bed_type: "lucid"
  bed_address: "DC:BB:48:42:D9:3E"
  mqtt_user: "mqttbed"
  mqtt_pass: "mqtt-bed"
  mqtt_server: "homeassistant.local"
  mqtt_port: 1883
  mqtt_topic: "bed"
schema:
  bed_type: "list(lucid|dewertokin|serta|jiecang)"
  bed_address: "match(^[A-z0-9]{2}:[A-z0-9]{2}:[A-z0-9]{2}:[A-z0-9]{2}:[A-z0-9]{2}:[A-z0-9]{2}$)"
  mqtt_user: "str?"
  mqtt_pass: "password?"
  mqtt_server: "str?"
  mqtt_port: "port?"
  mqtt_topic: "str?"
#image: "ghcr.io/dstarikov/{arch}-hass-mqtt-bed"
